//draw boilerplate
draw_self()
draw_set_font(MaryKate)
draw_text(128, 32, "Welcome to " + GAMENAME)
draw_set_colour(c_yellow)
draw_text(64, 128, "Your Name: > " + keyboard_string + " <")
draw_set_colour(c_lime)
//draw_text(64, 160, "Type your name above")
draw_text(64, 224, "Arrow Keys to move")
draw_text(64, 256, "Space to Undo")
draw_text(64, 288, "Escape to Return Here")
draw_text(64, 320, "Penguin for the Leaderboard")
draw_text(64, 384, "Please choose a Theme:")
draw_text(64, 800, "Artwork by www.shaelina.com")
draw_text(64, 832, "Music by www.youtube.com/@Wanye")